# Generated by Django 5.0.6 on 2024-05-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='about_us/background/')),
            ],
            options={
                'verbose_name_plural': 'Фон',
            },
        ),
        migrations.CreateModel(
            name='BackgroundMyWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='my_work/background/')),
            ],
            options={
                'verbose_name_plural': 'Фон',
            },
        ),
        migrations.CreateModel(
            name='BackgroundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='record/background/')),
            ],
            options={
                'verbose_name_plural': 'Фон',
            },
        ),
        migrations.CreateModel(
            name='BackgroundReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='reviews/background/')),
            ],
            options={
                'verbose_name_plural': 'Фон',
            },
        ),
        migrations.CreateModel(
            name='BackgroundService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='service/background/')),
            ],
            options={
                'verbose_name_plural': 'Фон',
            },
        ),
        migrations.CreateModel(
            name='ImageAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about_us/')),
            ],
            options={
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='ImageMyWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='my_works/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Мои работы',
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Услуги и цены',
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='TextAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Текс',
            },
        ),
    ]
