# Generated by Django 5.0.6 on 2024-05-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Услуги и цены'},
        ),
    ]
