# Generated by Django 5.0.6 on 2024-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemyworks',
            name='img',
            field=models.ImageField(upload_to='my_work/'),
        ),
    ]
