# Generated by Django 5.0.6 on 2024-05-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imagemyworks_alter_imageaboutus_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageaboutus',
            options={'verbose_name': 'Картинки "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='imagemyworks',
            options={'ordering': ['-img'], 'verbose_name': 'Мои работы'},
        ),
        migrations.AlterModelOptions(
            name='textaboutus',
            options={'verbose_name': 'Текс "О нас"'},
        ),
    ]
