# Generated by Django 5.0.6 on 2024-05-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_imageaboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageaboutus',
            options={'verbose_name': 'Картинки "О нас"', 'verbose_name_plural': 'Картинки "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='imagemyworks',
            options={'ordering': ['-img'], 'verbose_name': 'Мои работы', 'verbose_name_plural': 'Мои работы'},
        ),
        migrations.AlterModelOptions(
            name='textaboutus',
            options={'verbose_name': 'Текс "О нас"', 'verbose_name_plural': 'Текс "О нас"'},
        ),
    ]
