# Generated by Django 5.0.6 on 2024-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_imagemyworks_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageaboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imageaboutus',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
