# Generated by Django 5.0.6 on 2024-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imageaboutus_created_at_imageaboutus_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageaboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imageaboutus',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
