# Generated by Django 5.0.6 on 2024-05-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_imageaboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemyworks',
            options={'verbose_name': 'Мои работы', 'verbose_name_plural': 'Мои работы'},
        ),
    ]
