# Generated by Django 5.0.6 on 2024-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imagemyworks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemyworks',
            options={'ordering': ['-created_at'], 'verbose_name': 'Мои работы', 'verbose_name_plural': 'Мои работы'},
        ),
        migrations.AddField(
            model_name='imagemyworks',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
