# Generated by Django 5.0.6 on 2024-05-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_imagemyworks_options_imagemyworks_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemyworks',
            options={'ordering': ['-update_at'], 'verbose_name': 'Мои работы', 'verbose_name_plural': 'Мои работы'},
        ),
        migrations.AddField(
            model_name='imagemyworks',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imagemyworks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
