# Generated by Django 5.0.6 on 2024-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_imagemyworks_options_imagemyworks_update_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='about_us/background/')),
            ],
            options={
                'verbose_name': 'Фон "О нас"',
                'verbose_name_plural': 'Фон "О нас"',
            },
        ),
    ]
