# Generated by Django 5.0.6 on 2024-05-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='queue_number',
            field=models.PositiveIntegerField(),
        ),
    ]
