# Generated by Django 5.0.6 on 2024-05-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_service_price_alter_service_queue_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='queue_number',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
    ]
